// <auto-generated />
using System;
using FinancialAnalytics.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinancialAnalytics.Api.Migrations.FakeErp
{
    [DbContext(typeof(FakeErpDbContext))]
    [Migration("20260824132832_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinancialAnalytics.Api.ErpAccount", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AccountId");

                    b.HasIndex("AccountCode")
                        .IsUnique();

                    b.ToTable("Account", (string)null);

                    b.HasData(
                        new
                        {
                            AccountId = 1,
                            AccountCode = "4000",
                            AccountName = "Product Sales"
                        },
                        new
                        {
                            AccountId = 2,
                            AccountCode = "4010",
                            AccountName = "Service Sales"
                        },
                        new
                        {
                            AccountId = 3,
                            AccountCode = "5000",
                            AccountName = "Materials"
                        },
                        new
                        {
                            AccountId = 4,
                            AccountCode = "6000",
                            AccountName = "Salaries"
                        });
                });

            modelBuilder.Entity("FinancialAnalytics.Api.ErpEntity", b =>
                {
                    b.Property<int>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntityId"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .IsFixedLength();

                    b.Property<string>("EntityCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("EntityId");

                    b.HasIndex("EntityCode")
                        .IsUnique();

                    b.ToTable("Entity", (string)null);

                    b.HasData(
                        new
                        {
                            EntityId = 1,
                            CountryCode = "US",
                            EntityCode = "US",
                            EntityName = "Northstar US"
                        });
                });

            modelBuilder.Entity("FinancialAnalytics.Api.ErpTransaction", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date");

                    b.HasKey("TransactionId");

                    b.HasIndex("AccountId");

                    b.HasIndex("EntityId");

                    b.HasIndex("TransactionDate", "AccountId");

                    b.ToTable("Transaction", (string)null);

                    b.HasData(
                        new
                        {
                            TransactionId = "A001",
                            AccountId = 1,
                            Amount = 10000m,
                            CreatedAt = new DateTime(2026, 4, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            CurrencyCode = "USD",
                            Description = "Product Sales",
                            EntityId = 1,
                            TransactionDate = new DateOnly(2026, 1, 5)
                        },
                        new
                        {
                            TransactionId = "A002",
                            AccountId = 1,
                            Amount = 15000m,
                            CreatedAt = new DateTime(2026, 4, 1, 12, 1, 0, 0, DateTimeKind.Utc),
                            CurrencyCode = "USD",
                            Description = "Product Sales",
                            EntityId = 1,
                            TransactionDate = new DateOnly(2026, 1, 9)
                        },
                        new
                        {
                            TransactionId = "A003",
                            AccountId = 1,
                            Amount = 12000m,
                            CreatedAt = new DateTime(2026, 4, 1, 12, 2, 0, 0, DateTimeKind.Utc),
                            CurrencyCode = "USD",
                            Description = "Product Sales",
                            EntityId = 1,
                            TransactionDate = new DateOnly(2026, 1, 13)
                        },
                        new
                        {
                            TransactionId = "A004",
                            AccountId = 1,
                            Amount = 10000m,
                            CreatedAt = new DateTime(2026, 4, 1, 12, 3, 0, 0, DateTimeKind.Utc),
                            CurrencyCode = "USD",
                            Description = "Product Sales",
                            EntityId = 1,
                            TransactionDate = new DateOnly(2026, 1, 17)
                        },
                        new
                        {
                            TransactionId = "A005",
                            AccountId = 1,
                            Amount = 10000m,
                            CreatedAt = new DateTime(2026, 4, 1, 12, 4, 0, 0, DateTimeKind.Utc),
                            CurrencyCode = "USD",
                            Description = "Product Sales",
                            EntityId = 1,
                            TransactionDate = new DateOnly(2026, 1, 21)
                        },
                        new
                        {
                            TransactionId = "A006",
                            AccountId = 2,
                            Amount = 5000m,
                            CreatedAt = new DateTime(2026, 4, 1, 12, 5, 0, 0, DateTimeKind.Utc),
                            CurrencyCode = "USD",
                            Description = "Service Sales",
                            EntityId = 1,
                            TransactionDate = new DateOnly(2026, 1, 25)
                        },
                        new
                        {
                            TransactionId = "A007",
                            AccountId = 2,
                            Amount = 4000m,
                            CreatedAt = new DateTime(2026, 4, 1, 12, 6, 0, 0, DateTimeKind.Utc),
                            CurrencyCode = "USD",
                            Description = "Service Sales",
                            EntityId = 1,
                            TransactionDate = new DateOnly(2026, 1, 29)
                        },
                        new
                        {
                            TransactionId = "A008",
                            AccountId = 2,
                            Amount = 4000m,
                            CreatedAt = new DateTime(2026, 4, 1, 12, 7, 0, 0, DateTimeKind.Utc),
                            CurrencyCode = "USD",
                            Description = "Service Sales",
                            EntityId = 1,
                            TransactionDate = new DateOnly(2026, 2, 2)
                        },
                        new
                        {
                            TransactionId = "A009",
                            AccountId = 2,
                            Amount = 4000m,
                            CreatedAt = new DateTime(2026, 4, 1, 12, 8, 0, 0, DateTimeKind.Utc),
                            CurrencyCode = "USD",
                            Description = "Service Sales",
                            EntityId = 1,
                            TransactionDate = new DateOnly(2026, 2, 6)
                        },
                        new
                        {
                            TransactionId = "A010",
                            AccountId = 3,
                            Amount = -8000m,
                            CreatedAt = new DateTime(2026, 4, 1, 12, 9, 0, 0, DateTimeKind.Utc),
                            CurrencyCode = "USD",
                            Description = "Materials",
                            EntityId = 1,
                            TransactionDate = new DateOnly(2026, 2, 10)
                        },
                        new
                        {
                            TransactionId = "A011",
                            AccountId = 3,
                            Amount = -5000m,
                            CreatedAt = new DateTime(2026, 4, 1, 12, 10, 0, 0, DateTimeKind.Utc),
                            CurrencyCode = "USD",
                            Description = "Materials",
                            EntityId = 1,
                            TransactionDate = new DateOnly(2026, 2, 14)
                        },
                        new
                        {
                            TransactionId = "A012",
                            AccountId = 3,
                            Amount = -4000m,
                            CreatedAt = new DateTime(2026, 4, 1, 12, 11, 0, 0, DateTimeKind.Utc),
                            CurrencyCode = "USD",
                            Description = "Materials",
                            EntityId = 1,
                            TransactionDate = new DateOnly(2026, 2, 18)
                        },
                        new
                        {
                            TransactionId = "A013",
                            AccountId = 3,
                            Amount = -3000m,
                            CreatedAt = new DateTime(2026, 4, 1, 12, 12, 0, 0, DateTimeKind.Utc),
                            CurrencyCode = "USD",
                            Description = "Materials",
                            EntityId = 1,
                            TransactionDate = new DateOnly(2026, 2, 22)
                        },
                        new
                        {
                            TransactionId = "A014",
                            AccountId = 3,
                            Amount = -3000m,
                            CreatedAt = new DateTime(2026, 4, 1, 12, 13, 0, 0, DateTimeKind.Utc),
                            CurrencyCode = "USD",
                            Description = "Materials",
                            EntityId = 1,
                            TransactionDate = new DateOnly(2026, 2, 26)
                        },
                        new
                        {
                            TransactionId = "A015",
                            AccountId = 4,
                            Amount = -2000m,
                            CreatedAt = new DateTime(2026, 4, 1, 12, 14, 0, 0, DateTimeKind.Utc),
                            CurrencyCode = "USD",
                            Description = "Salaries",
                            EntityId = 1,
                            TransactionDate = new DateOnly(2026, 3, 2)
                        },
                        new
                        {
                            TransactionId = "A016",
                            AccountId = 4,
                            Amount = -1000m,
                            CreatedAt = new DateTime(2026, 4, 1, 12, 15, 0, 0, DateTimeKind.Utc),
                            CurrencyCode = "USD",
                            Description = "Salaries",
                            EntityId = 1,
                            TransactionDate = new DateOnly(2026, 3, 6)
                        },
                        new
                        {
                            TransactionId = "A017",
                            AccountId = 4,
                            Amount = -1000m,
                            CreatedAt = new DateTime(2026, 4, 1, 12, 16, 0, 0, DateTimeKind.Utc),
                            CurrencyCode = "USD",
                            Description = "Salaries",
                            EntityId = 1,
                            TransactionDate = new DateOnly(2026, 3, 10)
                        },
                        new
                        {
                            TransactionId = "A018",
                            AccountId = 4,
                            Amount = -1000m,
                            CreatedAt = new DateTime(2026, 4, 1, 12, 17, 0, 0, DateTimeKind.Utc),
                            CurrencyCode = "USD",
                            Description = "Salaries",
                            EntityId = 1,
                            TransactionDate = new DateOnly(2026, 3, 14)
                        },
                        new
                        {
                            TransactionId = "A019",
                            AccountId = 4,
                            Amount = -1000m,
                            CreatedAt = new DateTime(2026, 4, 1, 12, 18, 0, 0, DateTimeKind.Utc),
                            CurrencyCode = "USD",
                            Description = "Salaries",
                            EntityId = 1,
                            TransactionDate = new DateOnly(2026, 3, 18)
                        },
                        new
                        {
                            TransactionId = "A020",
                            AccountId = 4,
                            Amount = -1000m,
                            CreatedAt = new DateTime(2026, 4, 1, 12, 19, 0, 0, DateTimeKind.Utc),
                            CurrencyCode = "USD",
                            Description = "Salaries",
                            EntityId = 1,
                            TransactionDate = new DateOnly(2026, 3, 22)
                        });
                });

            modelBuilder.Entity("FinancialAnalytics.Api.ErpTransaction", b =>
                {
                    b.HasOne("FinancialAnalytics.Api.ErpAccount", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinancialAnalytics.Api.ErpEntity", "Entity")
                        .WithMany("Transactions")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("FinancialAnalytics.Api.ErpAccount", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FinancialAnalytics.Api.ErpEntity", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
