// <auto-generated />
using System;
using FinancialAnalytics.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinancialAnalytics.Api.Migrations.FinancialAnalytics
{
    [DbContext(typeof(FinancialAnalyticsDbContext))]
    [Migration("20260824132842_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinancialAnalytics.Api.DimAccount", b =>
                {
                    b.Property<int>("AccountKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountKey"));

                    b.Property<string>("AccountCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ParentAccountKey")
                        .HasColumnType("int");

                    b.HasKey("AccountKey");

                    b.HasIndex("AccountCode")
                        .IsUnique();

                    b.HasIndex("ParentAccountKey");

                    b.ToTable("DimAccount", (string)null);

                    b.HasData(
                        new
                        {
                            AccountKey = 1,
                            AccountCategory = "Revenue",
                            AccountCode = "REV-PROD",
                            AccountName = "Product Revenue"
                        },
                        new
                        {
                            AccountKey = 2,
                            AccountCategory = "Revenue",
                            AccountCode = "REV-SERV",
                            AccountName = "Service Revenue"
                        },
                        new
                        {
                            AccountKey = 3,
                            AccountCategory = "COGS",
                            AccountCode = "COGS-MAT",
                            AccountName = "Materials"
                        },
                        new
                        {
                            AccountKey = 4,
                            AccountCategory = "Operating Expense",
                            AccountCode = "OPEX-SAL",
                            AccountName = "Salaries"
                        });
                });

            modelBuilder.Entity("FinancialAnalytics.Api.DimCurrency", b =>
                {
                    b.Property<int>("CurrencyKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CurrencyKey"));

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CurrencyKey");

                    b.HasIndex("CurrencyCode")
                        .IsUnique();

                    b.ToTable("DimCurrency", (string)null);

                    b.HasData(
                        new
                        {
                            CurrencyKey = 1,
                            CurrencyCode = "USD",
                            CurrencyName = "US Dollar"
                        });
                });

            modelBuilder.Entity("FinancialAnalytics.Api.DimDate", b =>
                {
                    b.Property<int>("DateKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DateKey"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<byte>("Day")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Month")
                        .HasColumnType("tinyint");

                    b.Property<string>("MonthName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("Quarter")
                        .HasColumnType("tinyint");

                    b.Property<short>("Year")
                        .HasColumnType("smallint");

                    b.HasKey("DateKey");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("DimDate", (string)null);

                    b.HasData(
                        new
                        {
                            DateKey = 20260105,
                            Date = new DateOnly(2026, 1, 5),
                            Day = (byte)5,
                            Month = (byte)1,
                            MonthName = "January",
                            Quarter = (byte)1,
                            Year = (short)2026
                        },
                        new
                        {
                            DateKey = 20260109,
                            Date = new DateOnly(2026, 1, 9),
                            Day = (byte)9,
                            Month = (byte)1,
                            MonthName = "January",
                            Quarter = (byte)1,
                            Year = (short)2026
                        },
                        new
                        {
                            DateKey = 20260113,
                            Date = new DateOnly(2026, 1, 13),
                            Day = (byte)13,
                            Month = (byte)1,
                            MonthName = "January",
                            Quarter = (byte)1,
                            Year = (short)2026
                        },
                        new
                        {
                            DateKey = 20260117,
                            Date = new DateOnly(2026, 1, 17),
                            Day = (byte)17,
                            Month = (byte)1,
                            MonthName = "January",
                            Quarter = (byte)1,
                            Year = (short)2026
                        },
                        new
                        {
                            DateKey = 20260121,
                            Date = new DateOnly(2026, 1, 21),
                            Day = (byte)21,
                            Month = (byte)1,
                            MonthName = "January",
                            Quarter = (byte)1,
                            Year = (short)2026
                        },
                        new
                        {
                            DateKey = 20260125,
                            Date = new DateOnly(2026, 1, 25),
                            Day = (byte)25,
                            Month = (byte)1,
                            MonthName = "January",
                            Quarter = (byte)1,
                            Year = (short)2026
                        },
                        new
                        {
                            DateKey = 20260129,
                            Date = new DateOnly(2026, 1, 29),
                            Day = (byte)29,
                            Month = (byte)1,
                            MonthName = "January",
                            Quarter = (byte)1,
                            Year = (short)2026
                        },
                        new
                        {
                            DateKey = 20260202,
                            Date = new DateOnly(2026, 2, 2),
                            Day = (byte)2,
                            Month = (byte)2,
                            MonthName = "February",
                            Quarter = (byte)1,
                            Year = (short)2026
                        },
                        new
                        {
                            DateKey = 20260206,
                            Date = new DateOnly(2026, 2, 6),
                            Day = (byte)6,
                            Month = (byte)2,
                            MonthName = "February",
                            Quarter = (byte)1,
                            Year = (short)2026
                        },
                        new
                        {
                            DateKey = 20260210,
                            Date = new DateOnly(2026, 2, 10),
                            Day = (byte)10,
                            Month = (byte)2,
                            MonthName = "February",
                            Quarter = (byte)1,
                            Year = (short)2026
                        },
                        new
                        {
                            DateKey = 20260214,
                            Date = new DateOnly(2026, 2, 14),
                            Day = (byte)14,
                            Month = (byte)2,
                            MonthName = "February",
                            Quarter = (byte)1,
                            Year = (short)2026
                        },
                        new
                        {
                            DateKey = 20260218,
                            Date = new DateOnly(2026, 2, 18),
                            Day = (byte)18,
                            Month = (byte)2,
                            MonthName = "February",
                            Quarter = (byte)1,
                            Year = (short)2026
                        },
                        new
                        {
                            DateKey = 20260222,
                            Date = new DateOnly(2026, 2, 22),
                            Day = (byte)22,
                            Month = (byte)2,
                            MonthName = "February",
                            Quarter = (byte)1,
                            Year = (short)2026
                        },
                        new
                        {
                            DateKey = 20260226,
                            Date = new DateOnly(2026, 2, 26),
                            Day = (byte)26,
                            Month = (byte)2,
                            MonthName = "February",
                            Quarter = (byte)1,
                            Year = (short)2026
                        },
                        new
                        {
                            DateKey = 20260302,
                            Date = new DateOnly(2026, 3, 2),
                            Day = (byte)2,
                            Month = (byte)3,
                            MonthName = "March",
                            Quarter = (byte)1,
                            Year = (short)2026
                        },
                        new
                        {
                            DateKey = 20260306,
                            Date = new DateOnly(2026, 3, 6),
                            Day = (byte)6,
                            Month = (byte)3,
                            MonthName = "March",
                            Quarter = (byte)1,
                            Year = (short)2026
                        },
                        new
                        {
                            DateKey = 20260310,
                            Date = new DateOnly(2026, 3, 10),
                            Day = (byte)10,
                            Month = (byte)3,
                            MonthName = "March",
                            Quarter = (byte)1,
                            Year = (short)2026
                        },
                        new
                        {
                            DateKey = 20260314,
                            Date = new DateOnly(2026, 3, 14),
                            Day = (byte)14,
                            Month = (byte)3,
                            MonthName = "March",
                            Quarter = (byte)1,
                            Year = (short)2026
                        },
                        new
                        {
                            DateKey = 20260318,
                            Date = new DateOnly(2026, 3, 18),
                            Day = (byte)18,
                            Month = (byte)3,
                            MonthName = "March",
                            Quarter = (byte)1,
                            Year = (short)2026
                        },
                        new
                        {
                            DateKey = 20260322,
                            Date = new DateOnly(2026, 3, 22),
                            Day = (byte)22,
                            Month = (byte)3,
                            MonthName = "March",
                            Quarter = (byte)1,
                            Year = (short)2026
                        });
                });

            modelBuilder.Entity("FinancialAnalytics.Api.DimEntity", b =>
                {
                    b.Property<int>("EntityKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntityKey"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .IsFixedLength();

                    b.Property<string>("EntityCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("EntityKey");

                    b.HasIndex("EntityCode")
                        .IsUnique();

                    b.ToTable("DimEntity", (string)null);

                    b.HasData(
                        new
                        {
                            EntityKey = 1,
                            CountryCode = "US",
                            EntityCode = "US",
                            EntityName = "Northstar US"
                        });
                });

            modelBuilder.Entity("FinancialAnalytics.Api.FactGl", b =>
                {
                    b.Property<long>("FactGLKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FactGLKey"));

                    b.Property<int>("AccountKey")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CurrencyKey")
                        .HasColumnType("int");

                    b.Property<int>("DateKey")
                        .HasColumnType("int");

                    b.Property<int>("EntityKey")
                        .HasColumnType("int");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SourceTransactionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FactGLKey");

                    b.HasIndex("AccountKey");

                    b.HasIndex("CurrencyKey");

                    b.HasIndex("EntityKey");

                    b.HasIndex("SourceTransactionId")
                        .IsUnique();

                    b.HasIndex("DateKey", "AccountKey", "EntityKey", "CurrencyKey");

                    b.ToTable("FactGL", (string)null);
                });

            modelBuilder.Entity("FinancialAnalytics.Api.PipelineRun", b =>
                {
                    b.Property<long>("PipelineRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PipelineRunId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecordsAlreadyExisting")
                        .HasColumnType("int");

                    b.Property<int>("RecordsExtracted")
                        .HasColumnType("int");

                    b.Property<int>("RecordsFailed")
                        .HasColumnType("int");

                    b.Property<int>("RecordsInserted")
                        .HasColumnType("int");

                    b.Property<int>("RecordsLoaded")
                        .HasColumnType("int");

                    b.Property<int>("RecordsTransformed")
                        .HasColumnType("int");

                    b.Property<int>("RecordsValidated")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("PipelineRunId");

                    b.HasIndex("StartedAt");

                    b.ToTable("PipelineRun", (string)null);
                });

            modelBuilder.Entity("FinancialAnalytics.Api.StgTransaction", b =>
                {
                    b.Property<long>("StgTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StgTransactionId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("PipelineRunId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceAccountCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SourceAccountName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SourceEntityCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SourceTransactionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date");

                    b.HasKey("StgTransactionId");

                    b.HasIndex("PipelineRunId", "SourceTransactionId")
                        .IsUnique();

                    b.ToTable("StgTransaction", (string)null);
                });

            modelBuilder.Entity("FinancialAnalytics.Api.DimAccount", b =>
                {
                    b.HasOne("FinancialAnalytics.Api.DimAccount", "ParentAccount")
                        .WithMany("ChildAccounts")
                        .HasForeignKey("ParentAccountKey")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentAccount");
                });

            modelBuilder.Entity("FinancialAnalytics.Api.FactGl", b =>
                {
                    b.HasOne("FinancialAnalytics.Api.DimAccount", "Account")
                        .WithMany("Facts")
                        .HasForeignKey("AccountKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinancialAnalytics.Api.DimCurrency", "Currency")
                        .WithMany("Facts")
                        .HasForeignKey("CurrencyKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinancialAnalytics.Api.DimDate", "Date")
                        .WithMany("Facts")
                        .HasForeignKey("DateKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinancialAnalytics.Api.DimEntity", "Entity")
                        .WithMany("Facts")
                        .HasForeignKey("EntityKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Currency");

                    b.Navigation("Date");

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("FinancialAnalytics.Api.StgTransaction", b =>
                {
                    b.HasOne("FinancialAnalytics.Api.PipelineRun", "PipelineRun")
                        .WithMany("StagedTransactions")
                        .HasForeignKey("PipelineRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PipelineRun");
                });

            modelBuilder.Entity("FinancialAnalytics.Api.DimAccount", b =>
                {
                    b.Navigation("ChildAccounts");

                    b.Navigation("Facts");
                });

            modelBuilder.Entity("FinancialAnalytics.Api.DimCurrency", b =>
                {
                    b.Navigation("Facts");
                });

            modelBuilder.Entity("FinancialAnalytics.Api.DimDate", b =>
                {
                    b.Navigation("Facts");
                });

            modelBuilder.Entity("FinancialAnalytics.Api.DimEntity", b =>
                {
                    b.Navigation("Facts");
                });

            modelBuilder.Entity("FinancialAnalytics.Api.PipelineRun", b =>
                {
                    b.Navigation("StagedTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
